### ISSUE TITLE
Prepend filename command line switch

### ISSUE THREAD

**Issue by metbril** [novoid/appendfilename#3]
I am trying some of your tools and found a need to **prepend** some text to the filename. That is, between the date/timestamp and the original filename.

For example the command

    appendfilename --prepend --text="Invoice" *.pdf

would change the name of 

    2018-11-16 Apple 123456.pdf

to

    2018-11-16 Invoice Apple 123456.pdf

**Comment by novoid** [comment]
Hi @metbril,

I understand your use-case.

I thought about it and unfortunately, I have to decline this feature. And this is why:

First of all, the tool is (somewhat unfortunately in this case) named "appendfilename" which contradicts any prepending feature. If I would have this use-case, I'd probably write a different tool or think about renaming "appendfilename" which I don't for now.

Secondly, if I would add a pre-pending command line switch, I can think of people who wants to have this prepended string before the date/time-stamp. The semantics would suggest so as well. (I know that appending before the tags is a different example that might be mentioned here.)

A personal suggestion for a workaround: When I want to prepend a string to many files, I end up using [vidir](https://linux.die.net/man/1/vidir) which can be installed via the Debian package `moreutils`. It opens the current directory in vim where you can use the column-insert feature to add those prepend-strings. Emacs/dired offers the same feature as well: `dired-toggle-read-only`. Other file managers should support such a feature but I don't know of any other file manager that provides a good solution for it besides Emacs/dired and `vidir`.

I hope this helps your use-case for now.

**Comment by metbril** [comment]
Thanks for your comment. I understand why you don't want to update your tool.

I think I will build a dedicated tool myself (be it python or bash). Would you accept a PR if I should decide to make one?

**Comment by novoid** [comment]
Hi @metbril,

It's not the implementation effort that made me decide against your proposal - it's the implications of it that made me think. Therefore, I am currently not interested in accepting a PR for it. Sorry. Thanks for your proposal - very kind!
