### ISSUE TITLE
--remove option is not available, see your geeqie use case example where you use it

### ISSUE THREAD

**Issue by michaelsjackson** [novoid/appendfilename#8]
So which command can we use for removing previously added file name additions? Thanks in advance.

This does not work here.
`-x /home/mj/snippy/geeqie/appendfilename/appendfilename/__init__.py --remove "${@}"`

**Comment by novoid** [comment]
Hi,
There is no `--remove` parameter and I can not think of a straight-forward way of implementing it. If you've got a sane concept, please write it in a feature request issue here.
The only thing I can think of you might have seen is when I remove tags (using `filetags`) with the `--remove` option or prepend it with a minus character.

**Comment by michaelsjackson** [comment]
Why "you might have seen", it is in your main page. See your section "Integrating into Geeqie".

**Comment by novoid** [comment]
Excellent. You've found a copy & paste error of mine. Probably happened when updating this section with snippets from `filetags` and doing search&replace without checking properly. I'll fix it right now. Sorry for causing any fuzz with that.

Once again, I'm also in situations where I need to remove parts of file names. I'm using `vidir` from `moreutils` or Emacs dired with activated `Wdired`. However, I can not think of a good implementation on how `appendfilename` might support here, considering multiple selected files and such. If I can get my head wrapped around a good approach, I might as well implement it.

**Comment by michaelsjackson** [comment]
No thanks, if I know there is no such option, all is well.  I only do not want to miss any functionality which is available, maybe I had an older version I thought first.  Now all makes sense, appendfilename can only append or prepend, but can not remove them again, using -word, as you implemented for filetags I guess.  So the remove .sh example on the main page should be removed then as well. Thanks for sharing all your great tools here again. Have a nice day.
